"""create table t_customer,t_produt,t_install_order

Revision ID: 0d937a0e7aff
Revises: dcbdb7e94810
Create Date: 2018-05-03 14:11:31.359000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d937a0e7aff'
down_revision = 'dcbdb7e94810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_customer',
    sa.Column('FInterID', sa.Integer(), nullable=False),
    sa.Column('FCreator', sa.String(length=50), nullable=True),
    sa.Column('FCreateTime', sa.DateTime(), nullable=True),
    sa.Column('FModifier', sa.String(length=50), nullable=True),
    sa.Column('FModifyTime', sa.DateTime(), nullable=True),
    sa.Column('Name', sa.String(length=50), nullable=True),
    sa.Column('FullName', sa.String(length=100), nullable=True),
    sa.Column('Fax', sa.Integer(), nullable=True),
    sa.Column('Tel', sa.String(length=50), nullable=True),
    sa.Column('Address', sa.String(length=100), nullable=True),
    sa.Column('Note', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('FInterID')
    )
    op.create_table('t_product',
    sa.Column('FInterID', sa.Integer(), nullable=False),
    sa.Column('FCreator', sa.String(length=50), nullable=True),
    sa.Column('FCreateTime', sa.DateTime(), nullable=True),
    sa.Column('FModifier', sa.String(length=50), nullable=True),
    sa.Column('FModifyTime', sa.DateTime(), nullable=True),
    sa.Column('Code', sa.String(length=50), nullable=True),
    sa.Column('Name', sa.String(length=50), nullable=True),
    sa.Column('SupplierID', sa.Integer(), nullable=True),
    sa.Column('Note', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('FInterID')
    )
    op.create_table('t_install_order',
    sa.Column('FInterID', sa.Integer(), nullable=False),
    sa.Column('FCreator', sa.String(length=50), nullable=True),
    sa.Column('FCreateTime', sa.DateTime(), nullable=True),
    sa.Column('FModifier', sa.String(length=50), nullable=True),
    sa.Column('FModifyTime', sa.DateTime(), nullable=True),
    sa.Column('OrderNo', sa.String(length=50), nullable=True),
    sa.Column('Product_ID', sa.Integer(), nullable=True),
    sa.Column('Customer_ID', sa.Integer(), nullable=True),
    sa.Column('Qty', sa.Integer(), nullable=True),
    sa.Column('Tel', sa.String(length=50), nullable=True),
    sa.Column('Address', sa.String(length=100), nullable=True),
    sa.Column('Note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['Customer_ID'], ['t_customer.FInterID'], ),
    sa.ForeignKeyConstraint(['Product_ID'], ['t_product.FInterID'], ),
    sa.PrimaryKeyConstraint('FInterID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_install_order')
    op.drop_table('t_product')
    op.drop_table('t_customer')
    # ### end Alembic commands ###
